global:
  scrape_interval: 60s
  evaluation_interval: 60s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'nutanix'
    static_configs:
      - targets: ['nutanix-exporter:9090']
    scrape_interval: 60s
    scrape_timeout: 30s

  - job_name: 'pricing'
    static_configs:
      - targets: ['pricing:5000']
    scrape_interval: 60s
    metrics_path: /metrics
